PROGRAM MAIN_ACTKE

#ifdef __PGI
USE NVTX
#endif

USE YOMDATA

USE UTIL_MODEL_PHYSICS_MF_TYPE_MOD
USE UTIL_TCST_MOD
USE UTIL_TLDDH_MOD
USE UTIL_TMDDH_MOD

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE YOMMDDH              , ONLY : TMDDH
USE PARKIND1             , ONLY : JPIM,    JPRB

USE YOMCST               , ONLY : TCST
USE YOMLDDH              , ONLY : TLDDH

USE XRD_GETOPTIONS
USE XRD_UNIX_ENV

USE YOMHOOK

#include "stack.h"

USE STACK_MOD

USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : STDOUT => OUTPUT_UNIT

IMPLICIT NONE

TYPE(TCST)                                  :: YDCST
TYPE(TLDDH)                                 :: YDLDDH
TYPE(TMDDH)                                 :: YDMDDH
TYPE(MODEL_PHYSICS_MF_TYPE)                 :: YDML_PHY_MF
INTEGER(KIND=JPIM)                          :: KLON 
INTEGER(KIND=JPIM)                          :: KGPBLKS
INTEGER(KIND=JPIM)                          :: KTDIAT 
INTEGER(KIND=JPIM)                          :: KTDIAN 
INTEGER(KIND=JPIM)                          :: KLEV 
REAL(KIND=JPRB)             ,POINTER        :: PAPHI(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PAPHIF(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PAPRS(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PAPRSF(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PDELP(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PR(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PT(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PU(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQ(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQICONV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQLCONV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PLSCPE(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PCD(:,:)
REAL(KIND=JPRB)             ,POINTER        :: PCH(:,:)
REAL(KIND=JPRB)             ,POINTER        :: PGZ0(:,:)
REAL(KIND=JPRB)             ,POINTER        :: PTS(:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQS(:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQICE(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQLI(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PECT(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PPRODTH(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PNLAB(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PNLABCVP(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PKTROV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PKQROV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PKQLROV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PKUROV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PXTROV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PXUROV(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PNBVNO(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PNEBS(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQCS(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PNEBS0(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PQCS0(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PCOEFN(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PFECT(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PFECTI(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PECT1(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PTPRDY(:,:,:)
REAL(KIND=JPRB)             ,POINTER        :: PEDR(:,:,:)

#include "actke.intfb.h"
#include "actke_openacc.intfb.h"

CHARACTER (LEN=128) :: CLOUT
CHARACTER (LEN=128) :: CLCASE_IN
CHARACTER (LEN=128) :: CLCASE_OUT
LOGICAL :: LLVERBOSE, LLDIFF, LLSTAT
INTEGER, POINTER :: IBLOCKLIST (:)
TYPE(STACK) :: YLSTACK
INTEGER :: ISIZE4, ISIZE8
CHARACTER*64 :: CLMETHOD
INTEGER :: ITIME, NTIME
LOGICAL :: LLSAVE, LLEXIST
REAL(KIND=8) :: TSC, TEC, TSD, TED, ZTC, ZTD
INTEGER(KIND=JPIM) :: NPROMA, NGPBLKS
INTEGER :: IOUT
TYPE (DD12), POINTER :: YLD
INTEGER :: JLON, JBLK

#ifdef ARCH
CHARACTER (LEN=*), PARAMETER :: CLARCH = ARCH
#else
CHARACTER (LEN=*), PARAMETER :: CLARCH = 'unkwown'
#endif

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('MAIN_CUCALLN_MF', 0, ZHOOK_HANDLE)

YLD => NULL ()

CALL INITOPTIONS

NPROMA  = 0; CALL GETOPTION ("--nproma",  NPROMA)
NGPBLKS = 0; CALL GETOPTION ("--ngpblks", NGPBLKS)

CALL GETOPTION ("--case-in", CLCASE_IN, MND=.TRUE.)
CLCASE_OUT = ''; CALL GETOPTION ("--case-out", CLCASE_OUT)

CALL GETOPTION ("--verbose", LLVERBOSE)
CALL GETOPTION ("--diff", LLDIFF)
CALL GETOPTION ("--stat", LLSTAT)

#ifdef PARKIND1_SINGLE
ISIZE4 = 50;
ISIZE8 = 5;
#else
ISIZE4 = 5;
ISIZE8 = 50;
#endif
CALL GETOPTION ("--stack-size-4", ISIZE4)
CALL GETOPTION ("--stack-size-8", ISIZE8)
NTIME = 1; CALL GETOPTION ("--times", NTIME)

CLMETHOD = 'openmp'; CALL GETOPTION ("--method", CLMETHOD)

IBLOCKLIST => NULL ()
CALL GETOPTION ("--block-list", IBLOCKLIST)

LLSAVE = CLCASE_OUT /= ''

IF (LLSAVE) THEN
  CALL XRD_MKDIR (TRIM (CLCASE_OUT))
ENDIF

CLOUT = '-'; CALL GETOPTION ("--out", CLOUT)

#ifdef __PGI
CALL NVTXSTARTRANGE ("DUMMY")
#endif

#ifdef USE_OPENACC
!$ACC PARALLEL LOOP GANG PRIVATE (JBLK) VECTOR_LENGTH (32)
#endif

#ifdef USE_OPENMP
!$OMP TARGET TEAMS DISTRIBUTE PRIVATE (JBLK) THREAD_LIMIT (32)
#endif

DO JBLK = 1, 1

#ifdef USE_OPENACC
!$ACC LOOP VECTOR PRIVATE (JLON)
#endif

#ifdef USE_OPENMP
!$OMP PARALLEL DO SIMD PRIVATE (JLON)
#endif
  
  DO JLON = 1, 32
    IF (JLON == 33) PRINT *, JLON
  ENDDO

#ifdef USE_OPENACC
!$ACC END LOOP
#endif

#ifdef USE_OPENMP
!$OMP END PARALLEL DO SIMD
#endif

  
ENDDO

#ifdef USE_OPENACC
!$ACC END PARALLEL LOOP
#endif

#ifdef USE_OPENMP
!$OMP END TARGET TEAMS DISTRIBUTE
#endif

#ifdef __PGI
CALL NVTXENDRANGE
#endif


CALL CHECKOPTIONS

CALL LOADALL

IF (LLVERBOSE) THEN
WRITE (0, *) " NPROMA = ", NPROMA, " NGPBLKS = ", NGPBLKS, " KLEV = ", KLEV
WRITE (0, *) " ISIZE4 = ", ISIZE4, " ISIZE8 = ", ISIZE8, " NTIME = ", NTIME
ENDIF

IF (LLSAVE) THEN
  CALL SAVEIALL
ENDIF

CALL GET_TIME (TSD)

#ifdef USE_OPENACC
!$ACC DATA COPY (PAPHI, PAPHIF, PAPRS, PAPRSF, PDELP, PR, PT, PU, PV, PQ, PQICONV,  PQLCONV, PLSCPE, PCD, &
!$ACC          & PCH, PGZ0, PTS, PQS, PQICE, PQLI, PECT, PPRODTH,  PNLAB, PNLABCVP, PKTROV, PKQROV, PKQLROV, &
!$ACC          & PKUROV, PXTROV, PXUROV, PNBVNO,  PNEBS, PQCS, PNEBS0, PQCS0, PCOEFN, PFECT, PFECTI, PECT1, PTPRDY, PEDR) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')
#endif

#ifdef USE_OPENMP
!$OMP TARGET DATA MAP (TOFROM: &
!$OMP          & PAPHI, PAPHIF, PAPRS, PAPRSF, PDELP, PR, PT, PU, PV, PQ, PQICONV,  PQLCONV, PLSCPE, PCD, &
!$OMP          & PCH, PGZ0, PTS, PQS, PQICE, PQLI, PECT, PPRODTH,  PNLAB, PNLABCVP, PKTROV, PKQROV, PKQLROV, &
!$OMP          & PKUROV, PXTROV, PXUROV, PNBVNO,  PNEBS, PQCS, PNEBS0, PQCS0, PCOEFN, PFECT, PFECTI, PECT1, PTPRDY, PEDR) IF (TRIM (CLMETHOD) == 'openaccsinglecolumn')
#endif

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL COPY (YDCST)
  CALL COPY (YDLDDH)
  CALL COPY (YDMDDH)
  CALL COPY (YDML_PHY_MF)
ENDIF

CALL GET_TIME (TSC)

DO ITIME = 1, NTIME

  IF (TRIM (CLMETHOD) == 'openmp') THEN

!$OMP PARALLEL DO PRIVATE (JBLK)
    DO JBLK = 1, NGPBLKS

      CALL ACTKE (YDCST, &
      & YDLDDH, YDMDDH, &
      & YDML_PHY_MF, 1, NPROMA, NPROMA, KTDIAT, KTDIAN, KLEV,  &
      & PAPHI (:,:,JBLK), PAPHIF (:,:,JBLK), PAPRS (:,:,JBLK), PAPRSF (:,:,JBLK), PDELP (:,:,JBLK), PR (:,:,JBLK), PT (:,:,JBLK), &
      & PU (:,:,JBLK), PV (:,:,JBLK), PQ (:,:,JBLK), PQICONV (:,:,JBLK),  PQLCONV (:,:,JBLK), PLSCPE (:,:,JBLK), PCD (:,JBLK), &
      & PCH (:,JBLK), PGZ0 (:,JBLK), PTS (:,JBLK), PQS (:,JBLK), PQICE (:,:,JBLK), PQLI (:,:,JBLK), PECT (:,:,JBLK), &
      & PPRODTH (:,:,JBLK),  PNLAB (:,:,JBLK), PNLABCVP (:,:,JBLK), PKTROV (:,:,JBLK), PKQROV (:,:,JBLK), PKQLROV (:,:,JBLK), &
      & PKUROV (:,:,JBLK), PXTROV (:,:,JBLK), PXUROV (:,:,JBLK), PNBVNO (:,:,JBLK),  PNEBS (:,:,JBLK), PQCS (:,:,JBLK), PNEBS0 (:,:,JBLK), &
      & PQCS0 (:,:,JBLK), PCOEFN (:,:,JBLK), PFECT (:,:,JBLK), PFECTI (:,:,JBLK), PECT1 (:,:,JBLK), &
      & PTPRDY (:,:,JBLK), PEDR (:,:,JBLK))

    ENDDO
!$OMP END PARALLEL DO

  ELSEIF (TRIM (CLMETHOD) == 'openmpsinglecolumn') THEN
  
IF (ITIME == 1) THEN

    IF (ISIZE4 > 0) ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV * ISIZE4 * NGPBLKS))
    IF (ISIZE8 > 0) ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV * ISIZE8 * NGPBLKS))

ENDIF
    
!$OMP PARALLEL DO PRIVATE (JBLK, JLON, YLSTACK)
    DO JBLK = 1, NGPBLKS
      DO JLON = 1, NPROMA

        YLSTACK%L8 = stack_l8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U8 = stack_u8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%L4 = stack_l4 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U4 = stack_u4 (YSTACK, JBLK, NGPBLKS)

        CALL ACTKE_OPENACC (YDCST, &
        & YDLDDH, YDMDDH, &
        & YDML_PHY_MF, JLON, JLON, NPROMA, KTDIAT, KTDIAN, KLEV,  &
        & PAPHI (:,:,JBLK), PAPHIF (:,:,JBLK), PAPRS (:,:,JBLK), PAPRSF (:,:,JBLK), PDELP (:,:,JBLK), PR (:,:,JBLK), PT (:,:,JBLK), &
        & PU (:,:,JBLK), PV (:,:,JBLK), PQ (:,:,JBLK), PQICONV (:,:,JBLK),  PQLCONV (:,:,JBLK), PLSCPE (:,:,JBLK), PCD (:,JBLK), &
        & PCH (:,JBLK), PGZ0 (:,JBLK), PTS (:,JBLK), PQS (:,JBLK), PQICE (:,:,JBLK), PQLI (:,:,JBLK), PECT (:,:,JBLK), &
        & PPRODTH (:,:,JBLK),  PNLAB (:,:,JBLK), PNLABCVP (:,:,JBLK), PKTROV (:,:,JBLK), PKQROV (:,:,JBLK), PKQLROV (:,:,JBLK), &
        & PKUROV (:,:,JBLK), PXTROV (:,:,JBLK), PXUROV (:,:,JBLK), PNBVNO (:,:,JBLK),  PNEBS (:,:,JBLK), PQCS (:,:,JBLK), PNEBS0 (:,:,JBLK), &
        & PQCS0 (:,:,JBLK), PCOEFN (:,:,JBLK), PFECT (:,:,JBLK), PFECTI (:,:,JBLK), PECT1 (:,:,JBLK), &
        & PTPRDY (:,:,JBLK), PEDR (:,:,JBLK), &
        & YDSTACK=YLSTACK)

      ENDDO

    ENDDO
!$OMP END PARALLEL DO

  ELSEIF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN

IF (ITIME == 1) THEN

    ALLOCATE (YSTACK%ZDATA4 (NPROMA, KLEV *  ISIZE4 * NGPBLKS))
    ALLOCATE (YSTACK%ZDATA8 (NPROMA, KLEV *  ISIZE8 * NGPBLKS))

#ifdef USE_OPENACC
!$ACC ENTER DATA CREATE (YSTACK%ZDATA4)
!$ACC ENTER DATA CREATE (YSTACK%ZDATA8)
!$ACC ENTER DATA CREATE (YSTACK)
!$ACC UPDATE DEVICE (YSTACK)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA4)
!$ACC ENTER DATA ATTACH (YSTACK%ZDATA8)
#endif

#ifdef USE_OPENMP
!$OMP TARGET ENTER DATA MAP (TO:YSTACK,YSTACK%ZDATA4,YSTACK%ZDATA8)
#endif

ENDIF

#ifdef __PGI
CALL NVTXSTARTRANGE ("ACTKE_OPENACC")
#endif

#ifdef USE_OPENACC
!$ACC PARALLEL LOOP GANG &
!$ACC& PRESENT (YDCST, YDLDDH, YDMDDH, YDML_PHY_MF, YSTACK, PAPHI, PAPHIF, PAPRS, PAPRSF, PDELP, PR, PT, PU, PV, PQ, PQICONV, PQLCONV, &
!$ACC&         PLSCPE, PCD, PCH, PGZ0, PTS, PQS, PQICE, PQLI, PECT, PPRODTH,  PNLAB, PNLABCVP, PKTROV, PKQROV, PKQLROV, PKUROV, PXTROV, &
!$ACC&         PXUROV, PNBVNO, PNEBS, PQCS, PNEBS0, PQCS0, PCOEFN, PFECT, PFECTI, PECT1, PTPRDY, PEDR) &
!$ACC& PRIVATE (JBLK) &
!$ACC& VECTOR_LENGTH (NPROMA)
#endif

#ifdef USE_OPENMP
!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&PRIVATE (JBLK) &
!$OMP&NUM_TEAMS (NGPBLKS) &
!$OMP&THREAD_LIMIT (NPROMA)
#endif

    DO JBLK = 1, NGPBLKS

#ifdef USE_OPENACC
!$ACC LOOP VECTOR &
!$ACC&PRIVATE (JLON, YLSTACK) 
#endif

#ifdef USE_OPENMP
!$OMP PARALLEL DO SIMD PRIVATE (JLON, YLSTACK)
#endif

      DO JLON = 1, NPROMA

        YLSTACK%L8 = stack_l8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U8 = stack_u8 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%L4 = stack_l4 (YSTACK, JBLK, NGPBLKS)
        YLSTACK%U4 = stack_u4 (YSTACK, JBLK, NGPBLKS)

        CALL ACTKE_OPENACC (YDCST, &
        & YDLDDH, YDMDDH, &
        & YDML_PHY_MF, JLON, JLON, NPROMA, KTDIAT, KTDIAN, KLEV,  &
        & PAPHI (:,:,JBLK), PAPHIF (:,:,JBLK), PAPRS (:,:,JBLK), PAPRSF (:,:,JBLK), PDELP (:,:,JBLK), PR (:,:,JBLK), PT (:,:,JBLK), &
        & PU (:,:,JBLK), PV (:,:,JBLK), PQ (:,:,JBLK), PQICONV (:,:,JBLK),  PQLCONV (:,:,JBLK), PLSCPE (:,:,JBLK), PCD (:,JBLK), &
        & PCH (:,JBLK), PGZ0 (:,JBLK), PTS (:,JBLK), PQS (:,JBLK), PQICE (:,:,JBLK), PQLI (:,:,JBLK), PECT (:,:,JBLK), &
        & PPRODTH (:,:,JBLK),  PNLAB (:,:,JBLK), PNLABCVP (:,:,JBLK), PKTROV (:,:,JBLK), PKQROV (:,:,JBLK), PKQLROV (:,:,JBLK), &
        & PKUROV (:,:,JBLK), PXTROV (:,:,JBLK), PXUROV (:,:,JBLK), PNBVNO (:,:,JBLK),  PNEBS (:,:,JBLK), PQCS (:,:,JBLK), PNEBS0 (:,:,JBLK), &
        & PQCS0 (:,:,JBLK), PCOEFN (:,:,JBLK), PFECT (:,:,JBLK), PFECTI (:,:,JBLK), PECT1 (:,:,JBLK), &
        & PTPRDY (:,:,JBLK), PEDR (:,:,JBLK), &
        & YDSTACK=YLSTACK)

      ENDDO

#ifdef USE_OPENACC
!$ACC END LOOP
#endif

#ifdef USE_OPENMP
!$OMP END PARALLEL DO SIMD
#endif

    ENDDO

#ifdef USE_OPENACC
!$ACC END PARALLEL LOOP
#endif

#ifdef USE_OPENMP
!$OMP END TARGET TEAMS DISTRIBUTE
#endif

#ifdef __PGI
CALL NVTXENDRANGE
#endif

  ENDIF

ENDDO

CALL GET_TIME (TEC)

IF (TRIM (CLMETHOD) == 'openaccsinglecolumn') THEN
  CALL WIPE (YDCST)
  CALL WIPE (YDLDDH)
  CALL WIPE (YDMDDH)
  CALL WIPE (YDML_PHY_MF)
ENDIF

#ifdef USE_OPENACC
!$ACC END DATA
#endif

#ifdef USE_OPENMP
!$OMP END TARGET DATA
#endif

CALL GET_TIME (TED)

ZTC = TEC - TSC
ZTD = TED - TSD

LLEXIST = .FALSE.

IF (CLOUT == '-') THEN
  IOUT = STDOUT
ELSE
  IOUT = 77
  INQUIRE (FILE=TRIM (CLOUT), EXIST=LLEXIST)
  IF (LLEXIST) THEN
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='OLD', POSITION='APPEND')
  ELSE
    OPEN (IOUT, FILE=TRIM (CLOUT), FORM='FORMATTED', STATUS='NEW')
  ENDIF
ENDIF

IF (.NOT. LLEXIST) &
WRITE (IOUT, '(A16,";",A32,";",A8,";",A8,";",A8,4(";",A20))') &
              & "CLARCH", "CLMETHOD", "NPROMA", "NGPBLKS", "NTIME", &
              & "ZTCTOT", "ZTC", "ZTDTOT", "ZTD"

WRITE (IOUT, '(A16,";",A32,";",I8,";",I8,";",I8,4(";",E20.10))') &
              & CLARCH,  TRIM (CLMETHOD), NPROMA, NGPBLKS, NTIME, &
              & ZTC, ZTC / REAL (NPROMA*NGPBLKS*NTIME, 8), &
              & ZTD, ZTD / REAL (NPROMA*NGPBLKS*NTIME, 8)

IF (IOUT /= STDOUT) THEN
  CLOSE (IOUT)
ENDIF


IF (LLDIFF) THEN
  CALL DIFFALL
ENDIF

IF (LLSTAT) THEN
  CALL STATALL
ENDIF

IF (LLSAVE) THEN
  CALL SAVEOALL
ENDIF

IF (LHOOK) CALL DR_HOOK ('MAIN_ACTKE', 1, ZHOOK_HANDLE)

CONTAINS

SUBROUTINE LOADALL

INTEGER :: ILUNCI, ILUNFI

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_IN)//'/ACTKE.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_IN)//'/ACTKE.IN.dat',    FORM='UNFORMATTED')

CALL LOAD (ILUNCI,   YDCST)
CALL LOAD (ILUNCI,   YDLDDH)
CALL LOAD (ILUNCI,   YDMDDH)
CALL LOAD (ILUNCI,   YDML_PHY_MF)
CALL LOAD (ILUNCI,   KLON)
CALL LOAD (ILUNCI,   KGPBLKS)
CALL LOAD (ILUNCI,   KTDIAT)
CALL LOAD (ILUNCI,   KTDIAN)
CALL LOAD (ILUNCI,   KLEV)


IF (NPROMA == 0) NPROMA = KLON
IF (NGPBLKS == 0) THEN
  IF (ASSOCIATED (IBLOCKLIST)) THEN
    NGPBLKS = SIZE (IBLOCKLIST)
  ELSE
    NGPBLKS = KGPBLKS
  ENDIF
ENDIF

IF ((NPROMA /= KLON) .OR. (NGPBLKS /= KGPBLKS) .OR. ASSOCIATED (IBLOCKLIST)) THEN

  ALLOCATE (YLD)

  IF (ASSOCIATED (IBLOCKLIST)) THEN
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS], IBLOCKLIST)
  ELSE
    CALL YLD%INIT ([KLON, KGPBLKS], [NPROMA, NGPBLKS])
  ENDIF

  NPROMA = YLD%IPROMA2
  NGPBLKS = YLD%IGPBLKS2

ENDIF

KLON = NPROMA
KGPBLKS = NGPBLKS

CALL LOAD (ILUNFI,   PAPHI    , YDD=YLD)
CALL LOAD (ILUNFI,   PAPHIF   , YDD=YLD)
CALL LOAD (ILUNFI,   PAPRS    , YDD=YLD)
CALL LOAD (ILUNFI,   PAPRSF   , YDD=YLD)
CALL LOAD (ILUNFI,   PDELP    , YDD=YLD)
CALL LOAD (ILUNFI,   PR       , YDD=YLD)
CALL LOAD (ILUNFI,   PT       , YDD=YLD)
CALL LOAD (ILUNFI,   PU       , YDD=YLD)
CALL LOAD (ILUNFI,   PV       , YDD=YLD)
CALL LOAD (ILUNFI,   PQ       , YDD=YLD)
CALL LOAD (ILUNFI,   PQICONV  , YDD=YLD)
CALL LOAD (ILUNFI,   PQLCONV  , YDD=YLD)
CALL LOAD (ILUNFI,   PLSCPE   , YDD=YLD)
CALL LOAD (ILUNFI,   PCD      , YDD=YLD)
CALL LOAD (ILUNFI,   PCH      , YDD=YLD)
CALL LOAD (ILUNFI,   PGZ0     , YDD=YLD)
CALL LOAD (ILUNFI,   PTS      , YDD=YLD)
CALL LOAD (ILUNFI,   PQS      , YDD=YLD)
CALL LOAD (ILUNFI,   PQICE    , YDD=YLD)
CALL LOAD (ILUNFI,   PQLI     , YDD=YLD)
CALL LOAD (ILUNFI,   PECT     , YDD=YLD)
CALL LOAD (ILUNFI,   PPRODTH  , YDD=YLD)
CALL LOAD (ILUNFI,   PNLAB    , YDD=YLD)
CALL LOAD (ILUNFI,   PNLABCVP , YDD=YLD)
CALL LOAD (ILUNFI,   PKTROV   , YDD=YLD)
CALL LOAD (ILUNFI,   PKQROV   , YDD=YLD)
CALL LOAD (ILUNFI,   PKQLROV  , YDD=YLD)
CALL LOAD (ILUNFI,   PKUROV   , YDD=YLD)
CALL LOAD (ILUNFI,   PXTROV   , YDD=YLD)
CALL LOAD (ILUNFI,   PXUROV   , YDD=YLD)
CALL LOAD (ILUNFI,   PNBVNO   , YDD=YLD)
CALL LOAD (ILUNFI,   PNEBS    , YDD=YLD)
CALL LOAD (ILUNFI,   PQCS     , YDD=YLD)
CALL LOAD (ILUNFI,   PNEBS0   , YDD=YLD)
CALL LOAD (ILUNFI,   PQCS0    , YDD=YLD)
CALL LOAD (ILUNFI,   PCOEFN   , YDD=YLD)
CALL LOAD (ILUNFI,   PFECT    , YDD=YLD)
CALL LOAD (ILUNFI,   PFECTI   , YDD=YLD)
CALL LOAD (ILUNFI,   PECT1    , YDD=YLD)
CALL LOAD (ILUNFI,   PTPRDY   , YDD=YLD)
CALL LOAD (ILUNFI,   PEDR     , YDD=YLD)

CLOSE (ILUNCI)
CLOSE (ILUNFI)

END SUBROUTINE

SUBROUTINE STATALL

INTEGER :: ILUNFO

IF (LLVERBOSE) PRINT *, " STAT..."

WRITE (*, '(A32," ",A30," ",A30," ",A30," ",A30)') "NAME", "AVG", "MAX", "AVGDIFF", "MAXDIFF"

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/ACTKE.OUT.dat', FORM='UNFORMATTED')
CALL STAT ("PQICE   ",  PQICE   , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PQLI    ",  PQLI    , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PECT    ",  PECT    , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PPRODTH ",  PPRODTH , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PNLAB   ",  PNLAB   , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PNLABCVP",  PNLABCVP, KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PKTROV  ",  PKTROV  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PKQROV  ",  PKQROV  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PKQLROV ",  PKQLROV , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PKUROV  ",  PKUROV  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PXTROV  ",  PXTROV  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PXUROV  ",  PXUROV  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PNBVNO  ",  PNBVNO  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PNEBS   ",  PNEBS   , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PQCS    ",  PQCS    , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PNEBS0  ",  PNEBS0  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PQCS0   ",  PQCS0   , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PCOEFN  ",  PCOEFN  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFECT   ",  PFECT   , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PFECTI  ",  PFECTI  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PECT1   ",  PECT1   , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PTPRDY  ",  PTPRDY  , KLUN=ILUNFO, YDD=YLD)
CALL STAT ("PEDR    ",  PEDR    , KLUN=ILUNFO, YDD=YLD)
CLOSE (ILUNFO)

IF (LLVERBOSE) PRINT *, " ...STAT"

END SUBROUTINE

SUBROUTINE DIFFALL

INTEGER :: ILUNFO

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_IN)//'/ACTKE.OUT.dat', FORM='UNFORMATTED')
CALL DIFF ("PQICE   ",  PQICE   , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PQLI    ",  PQLI    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PECT    ",  PECT    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PPRODTH ",  PPRODTH , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PNLAB   ",  PNLAB   , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PNLABCVP",  PNLABCVP, KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PKTROV  ",  PKTROV  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PKQROV  ",  PKQROV  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PKQLROV ",  PKQLROV , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PKUROV  ",  PKUROV  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PXTROV  ",  PXTROV  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PXUROV  ",  PXUROV  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PNBVNO  ",  PNBVNO  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PNEBS   ",  PNEBS   , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PQCS    ",  PQCS    , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PNEBS0  ",  PNEBS0  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PQCS0   ",  PQCS0   , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PCOEFN  ",  PCOEFN  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFECT   ",  PFECT   , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PFECTI  ",  PFECTI  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PECT1   ",  PECT1   , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PTPRDY  ",  PTPRDY  , KLUN=ILUNFO, YDD=YLD)
CALL DIFF ("PEDR    ",  PEDR    , KLUN=ILUNFO, YDD=YLD)
CLOSE (ILUNFO)

END SUBROUTINE

SUBROUTINE SAVEIALL

INTEGER :: ILUNCI, ILUNFI

ILUNCI = 77
ILUNFI = 78

OPEN (ILUNCI, NAME=TRIM (CLCASE_OUT)//'/ACTKE.CONST.dat', FORM='UNFORMATTED')
OPEN (ILUNFI, NAME=TRIM (CLCASE_OUT)//'/ACTKE.IN.dat',    FORM='UNFORMATTED')

CALL SAVE (ILUNCI,   YDCST)
CALL SAVE (ILUNCI,   YDLDDH)
CALL SAVE (ILUNCI,   YDMDDH)
CALL SAVE (ILUNCI,   YDML_PHY_MF)
CALL SAVE (ILUNCI,   NPROMA)
CALL SAVE (ILUNCI,   NGPBLKS)
CALL SAVE (ILUNCI,   KTDIAT)
CALL SAVE (ILUNCI,   KTDIAN)
CALL SAVE (ILUNCI,   KLEV)
CALL SAVE (ILUNFI,   PAPHI     , KLBOUND=LBOUND (PAPHI))
CALL SAVE (ILUNFI,   PAPHIF    , KLBOUND=LBOUND (PAPHIF))
CALL SAVE (ILUNFI,   PAPRS     , KLBOUND=LBOUND (PAPRS))
CALL SAVE (ILUNFI,   PAPRSF    , KLBOUND=LBOUND (PAPRSF))
CALL SAVE (ILUNFI,   PDELP     , KLBOUND=LBOUND (PDELP))
CALL SAVE (ILUNFI,   PR        , KLBOUND=LBOUND (PR))
CALL SAVE (ILUNFI,   PT        , KLBOUND=LBOUND (PT))
CALL SAVE (ILUNFI,   PU        , KLBOUND=LBOUND (PU))
CALL SAVE (ILUNFI,   PV        , KLBOUND=LBOUND (PV))
CALL SAVE (ILUNFI,   PQ        , KLBOUND=LBOUND (PQ))
CALL SAVE (ILUNFI,   PQICONV   , KLBOUND=LBOUND (PQICONV))
CALL SAVE (ILUNFI,   PQLCONV   , KLBOUND=LBOUND (PQLCONV))
CALL SAVE (ILUNFI,   PLSCPE    , KLBOUND=LBOUND (PLSCPE))
CALL SAVE (ILUNFI,   PCD       , KLBOUND=LBOUND (PCD))
CALL SAVE (ILUNFI,   PCH       , KLBOUND=LBOUND (PCH))
CALL SAVE (ILUNFI,   PGZ0      , KLBOUND=LBOUND (PGZ0))
CALL SAVE (ILUNFI,   PTS       , KLBOUND=LBOUND (PTS))
CALL SAVE (ILUNFI,   PQS       , KLBOUND=LBOUND (PQS))
CALL SAVE (ILUNFI,   PQICE     , KLBOUND=LBOUND (PQICE))
CALL SAVE (ILUNFI,   PQLI      , KLBOUND=LBOUND (PQLI))
CALL SAVE (ILUNFI,   PECT      , KLBOUND=LBOUND (PECT))
CALL SAVE (ILUNFI,   PPRODTH   , KLBOUND=LBOUND (PPRODTH))
CALL SAVE (ILUNFI,   PNLAB     , KLBOUND=LBOUND (PNLAB))
CALL SAVE (ILUNFI,   PNLABCVP  , KLBOUND=LBOUND (PNLABCVP))
CALL SAVE (ILUNFI,   PKTROV    , KLBOUND=LBOUND (PKTROV))
CALL SAVE (ILUNFI,   PKQROV    , KLBOUND=LBOUND (PKQROV))
CALL SAVE (ILUNFI,   PKQLROV   , KLBOUND=LBOUND (PKQLROV))
CALL SAVE (ILUNFI,   PKUROV    , KLBOUND=LBOUND (PKUROV))
CALL SAVE (ILUNFI,   PXTROV    , KLBOUND=LBOUND (PXTROV))
CALL SAVE (ILUNFI,   PXUROV    , KLBOUND=LBOUND (PXUROV))
CALL SAVE (ILUNFI,   PNBVNO    , KLBOUND=LBOUND (PNBVNO))
CALL SAVE (ILUNFI,   PNEBS     , KLBOUND=LBOUND (PNEBS))
CALL SAVE (ILUNFI,   PQCS      , KLBOUND=LBOUND (PQCS))
CALL SAVE (ILUNFI,   PNEBS0    , KLBOUND=LBOUND (PNEBS0))
CALL SAVE (ILUNFI,   PQCS0     , KLBOUND=LBOUND (PQCS0))
CALL SAVE (ILUNFI,   PCOEFN    , KLBOUND=LBOUND (PCOEFN))
CALL SAVE (ILUNFI,   PFECT     , KLBOUND=LBOUND (PFECT))
CALL SAVE (ILUNFI,   PFECTI    , KLBOUND=LBOUND (PFECTI))
CALL SAVE (ILUNFI,   PECT1     , KLBOUND=LBOUND (PECT1))
CALL SAVE (ILUNFI,   PTPRDY    , KLBOUND=LBOUND (PTPRDY))
CALL SAVE (ILUNFI,   PEDR      , KLBOUND=LBOUND (PEDR))

CLOSE (ILUNFI)
CLOSE (ILUNCI)

END SUBROUTINE

SUBROUTINE SAVEOALL

INTEGER :: ILUNFO

ILUNFO = 79
OPEN (ILUNFO, NAME=TRIM (CLCASE_OUT)//'/ACTKE.OUT.dat', FORM='UNFORMATTED')
CALL SAVE (ILUNFO, PQICE   , KLBOUND=LBOUND(PQICE))
CALL SAVE (ILUNFO, PQLI    , KLBOUND=LBOUND(PQLI))
CALL SAVE (ILUNFO, PECT    , KLBOUND=LBOUND(PECT))
CALL SAVE (ILUNFO, PPRODTH , KLBOUND=LBOUND(PPRODTH))
CALL SAVE (ILUNFO, PNLAB   , KLBOUND=LBOUND(PNLAB))
CALL SAVE (ILUNFO, PNLABCVP, KLBOUND=LBOUND(PNLABCVP))
CALL SAVE (ILUNFO, PKTROV  , KLBOUND=LBOUND(PKTROV))
CALL SAVE (ILUNFO, PKQROV  , KLBOUND=LBOUND(PKQROV))
CALL SAVE (ILUNFO, PKQLROV , KLBOUND=LBOUND(PKQLROV))
CALL SAVE (ILUNFO, PKUROV  , KLBOUND=LBOUND(PKUROV))
CALL SAVE (ILUNFO, PXTROV  , KLBOUND=LBOUND(PXTROV))
CALL SAVE (ILUNFO, PXUROV  , KLBOUND=LBOUND(PXUROV))
CALL SAVE (ILUNFO, PNBVNO  , KLBOUND=LBOUND(PNBVNO))
CALL SAVE (ILUNFO, PNEBS   , KLBOUND=LBOUND(PNEBS))
CALL SAVE (ILUNFO, PQCS    , KLBOUND=LBOUND(PQCS))
CALL SAVE (ILUNFO, PNEBS0  , KLBOUND=LBOUND(PNEBS0))
CALL SAVE (ILUNFO, PQCS0   , KLBOUND=LBOUND(PQCS0))
CALL SAVE (ILUNFO, PCOEFN  , KLBOUND=LBOUND(PCOEFN))
CALL SAVE (ILUNFO, PFECT   , KLBOUND=LBOUND(PFECT))
CALL SAVE (ILUNFO, PFECTI  , KLBOUND=LBOUND(PFECTI))
CALL SAVE (ILUNFO, PECT1   , KLBOUND=LBOUND(PECT1))
CALL SAVE (ILUNFO, PTPRDY  , KLBOUND=LBOUND(PTPRDY))
CALL SAVE (ILUNFO, PEDR    , KLBOUND=LBOUND(PEDR))
CLOSE (ILUNFO)

END SUBROUTINE

END PROGRAM



