MODULE STACK_MOD

USE PARKIND1, ONLY : JPRB, JPIM, JPIA
USE ISO_C_BINDING, ONLY : C_F_POINTER, C_LOC

IMPLICIT NONE

TYPE STACK_DATA
  REAL (KIND=4), POINTER :: ZDATA4 (:,:)
  REAL (KIND=8), POINTER :: ZDATA8 (:,:)
END TYPE

TYPE STACK
  INTEGER*4 :: L4
  INTEGER*4 :: U4
  INTEGER*4 :: L8
  INTEGER*4 :: U8
END TYPE

TYPE (STACK_DATA) :: YSTACK

PUBLIC :: STACK, YSTACK, C_F_POINTER, C_LOC

!$OMP DECLARE TARGET (YSTACK)

END
