MODULE STACK_MOD

USE PARKIND1, ONLY : JPRB, JPIM, JPIA
USE ISO_C_BINDING, ONLY : C_PTR

IMPLICIT NONE

TYPE STACK_DATA
  REAL (KIND=4), POINTER :: ZDATA4 (:,:,:,:)
  REAL (KIND=8), POINTER :: ZDATA8 (:,:,:,:)
  INTEGER*8 :: IALIGN
END TYPE

TYPE STACK
  INTEGER*8 :: L4
  INTEGER*8 :: U4
  INTEGER*8 :: L8
  INTEGER*8 :: U8
END TYPE

TYPE (STACK_DATA) :: YSTACK

TYPE (C_PTR) :: CPTR

PUBLIC :: STACK, YSTACK, CPTR


END
