FC=flang -march=native  -Qunused-arguments -fPIC -ffree-form -cpp -fbackslash -fconvert=big-endian -O2 -ffp-contract=off -DARCH="'afar221ompd'" -fopenmp -Werror -fPIC -fopenmp --offload-arch=gfx942 -DUSE_OPENMP -lflang_rt.hostdevice
CC=clang -march=native  -Qunused-arguments -fPIC -fopenmp -O2 -ffp-contract=off
