
SUBROUTINE STACK_ALLOC_I4_1 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

INTEGER (4), POINTER, CONTIGUOUS :: KPTR (:)
INTEGER :: LBOUNDS , UBOUNDS , ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = 1

KPTR (LBOUNDS :UBOUNDS ) => YSTACK%IDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_I4_2 (KPTR, LBOUNDS1, LBOUNDS2, UBOUNDS1, UBOUNDS2, YDSTACK) 

!$omp declare target

INTEGER (4), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS1,LBOUNDS2, UBOUNDS1, UBOUNDS2, ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = UBOUNDS2 - LBOUNDS2 + 1

KPTR (LBOUNDS1:UBOUNDS1, LBOUNDS2:UBOUNDS2) => YSTACK%IDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_L4_1 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

LOGICAL (4), POINTER, CONTIGUOUS :: KPTR (:)
INTEGER :: LBOUNDS , UBOUNDS, ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = 1

KPTR (LBOUNDS :UBOUNDS ) => YSTACK%LDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_L4_2 (KPTR, LBOUNDS1, LBOUNDS2, UBOUNDS1, UBOUNDS2, YDSTACK) 

!$omp declare target

LOGICAL (4), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS1, LBOUNDS2, UBOUNDS1, UBOUNDS2, ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = UBOUNDS2 - LBOUNDS2 + 1

KPTR (LBOUNDS1:UBOUNDS1, LBOUNDS2:UBOUNDS2) => YSTACK%LDATA4 (:,YDSTACK%L4+1:YDSTACK%L4+ISIZE)
YDSTACK%L4 = YDSTACK%L4 + ISIZE
IF (YDSTACK%L4 > YDSTACK%U4) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_R8_1 (KPTR, LBOUNDS, UBOUNDS, YDSTACK) 

!$omp declare target

REAL (8), POINTER, CONTIGUOUS :: KPTR (:)
INTEGER :: LBOUNDS, UBOUNDS, ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = 1

KPTR (LBOUNDS:UBOUNDS) => YSTACK%ZDATA8 (:,YDSTACK%L8+1:YDSTACK%L8+ISIZE)
YDSTACK%L8 = YDSTACK%L8 + ISIZE
IF (YDSTACK%L8 > YDSTACK%U8) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_R8_2 (KPTR, LBOUNDS1, LBOUNDS2, UBOUNDS1, UBOUNDS2, YDSTACK) 

!$omp declare target

REAL (8), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS1, LBOUNDS2, UBOUNDS1, UBOUNDS2, ISIZE
TYPE (STACK) :: YDSTACK

ISIZE = UBOUNDS2 - LBOUNDS2 + 1
KPTR (LBOUNDS1:UBOUNDS1, LBOUNDS2:UBOUNDS2) => YSTACK%ZDATA8 (:,YDSTACK%L8+1:YDSTACK%L8+ISIZE)
YDSTACK%L8 = YDSTACK%L8 + ISIZE
IF (YDSTACK%L8 > YDSTACK%U8) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_R8_2_p (KPTR, LBOUNDS, UBOUNDS, YDSTACK,tab,jlon) 

!$omp declare target

REAL (8), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS (2), UBOUNDS (2), ISIZE
TYPE (STACK) :: YDSTACK
integer :: tab(:,:)
integer :: jlon
tab(jlon,1)=lbounds(2)
tab(jlon,2)=ubounds(2)
ISIZE = UBOUNDS (2) - LBOUNDS (2) + 1
tab(jlon,3)=isize
tab(jlon,4)=lbounds(1)
tab(jlon,5)=ubounds(1)

KPTR (LBOUNDS (1):UBOUNDS (1), LBOUNDS (2):UBOUNDS (2)) => YSTACK%ZDATA8 (:,YDSTACK%L8+1:YDSTACK%L8+ISIZE)
YDSTACK%L8 = YDSTACK%L8 + ISIZE
IF (YDSTACK%L8 > YDSTACK%U8) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

SUBROUTINE STACK_ALLOC_R8_2_p2 (KPTR, LBOUNDS1, LBOUNDS2,UBOUNDS1,UBOUNDS2, YDSTACK,tab,jlon) 

!$omp declare target

REAL (8), POINTER, CONTIGUOUS :: KPTR (:,:)
INTEGER :: LBOUNDS1,LBOUNDS2,UBOUNDS1, UBOUNDS2, ISIZE
TYPE (STACK) :: YDSTACK
integer :: tab(:,:)
integer :: jlon
tab(jlon,1)=lbounds2
tab(jlon,2)=ubounds2
ISIZE = UBOUNDS2 - LBOUNDS2 + 1
tab(jlon,3)=isize
tab(jlon,4)=lbounds1
tab(jlon,5)=ubounds1

KPTR (LBOUNDS1:UBOUNDS1 , LBOUNDS2 :UBOUNDS2) => YSTACK%ZDATA8 (:,YDSTACK%L8+1:YDSTACK%L8+ISIZE)
YDSTACK%L8 = YDSTACK%L8 + ISIZE
IF (YDSTACK%L8 > YDSTACK%U8) THEN 
  CALL ABOR1_ACC(__FILE__)
ENDIF

END SUBROUTINE

