MODULE UTIL_TAIOP_MOD

#include "util.h"

USE YOAIOP, ONLY : TAIOP

INTERFACE SAVE
MODULE PROCEDURE SAVE_TAIOP
END INTERFACE

INTERFACE LOAD
MODULE PROCEDURE LOAD_TAIOP
END INTERFACE

INTERFACE COPY
MODULE PROCEDURE COPY_TAIOP
END INTERFACE

INTERFACE HOST
MODULE PROCEDURE HOST_TAIOP
END INTERFACE

     
INTERFACE CRC64
MODULE PROCEDURE CRC64_TAIOP
END INTERFACE

INTERFACE WIPE
MODULE PROCEDURE WIPE_TAIOP
END INTERFACE

INTERFACE SIZE
MODULE PROCEDURE SIZE_TAIOP
END INTERFACE


CONTAINS

SUBROUTINE SAVE_TAIOP (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TAIOP), INTENT (IN), TARGET :: YD
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL
WRITE (KLUN) YD%NAEROMR
WRITE (KLUN) YD%NWAVSW
WRITE (KLUN) YD%NWAVLW
WRITE (KLUN) YD%NRELHU
LRSWAME = ALLOCATED (YD%RSWAME)
WRITE (KLUN) LRSWAME
IF (LRSWAME) THEN
  WRITE (KLUN) LBOUND (YD%RSWAME)
  WRITE (KLUN) UBOUND (YD%RSWAME)
  WRITE (KLUN) YD%RSWAME
ENDIF
LRLWAME = ALLOCATED (YD%RLWAME)
WRITE (KLUN) LRLWAME
IF (LRLWAME) THEN
  WRITE (KLUN) LBOUND (YD%RLWAME)
  WRITE (KLUN) UBOUND (YD%RLWAME)
  WRITE (KLUN) YD%RLWAME
ENDIF
LRSWAAS = ALLOCATED (YD%RSWAAS)
WRITE (KLUN) LRSWAAS
IF (LRSWAAS) THEN
  WRITE (KLUN) LBOUND (YD%RSWAAS)
  WRITE (KLUN) UBOUND (YD%RSWAAS)
  WRITE (KLUN) YD%RSWAAS
ENDIF
LRLWAAS = ALLOCATED (YD%RLWAAS)
WRITE (KLUN) LRLWAAS
IF (LRLWAAS) THEN
  WRITE (KLUN) LBOUND (YD%RLWAAS)
  WRITE (KLUN) UBOUND (YD%RLWAAS)
  WRITE (KLUN) YD%RLWAAS
ENDIF
LRSWASS = ALLOCATED (YD%RSWASS)
WRITE (KLUN) LRSWASS
IF (LRSWASS) THEN
  WRITE (KLUN) LBOUND (YD%RSWASS)
  WRITE (KLUN) UBOUND (YD%RSWASS)
  WRITE (KLUN) YD%RSWASS
ENDIF
LRLWASS = ALLOCATED (YD%RLWASS)
WRITE (KLUN) LRLWASS
IF (LRLWASS) THEN
  WRITE (KLUN) LBOUND (YD%RLWASS)
  WRITE (KLUN) UBOUND (YD%RLWASS)
  WRITE (KLUN) YD%RLWASS
ENDIF
LRSWWL = ALLOCATED (YD%RSWWL)
WRITE (KLUN) LRSWWL
IF (LRSWWL) THEN
  WRITE (KLUN) LBOUND (YD%RSWWL)
  WRITE (KLUN) UBOUND (YD%RSWWL)
  WRITE (KLUN) YD%RSWWL
ENDIF
LRLWWL = ALLOCATED (YD%RLWWL)
WRITE (KLUN) LRLWWL
IF (LRLWWL) THEN
  WRITE (KLUN) LBOUND (YD%RLWWL)
  WRITE (KLUN) UBOUND (YD%RLWWL)
  WRITE (KLUN) YD%RLWWL
ENDIF
LRSUNFR = ALLOCATED (YD%RSUNFR)
WRITE (KLUN) LRSUNFR
IF (LRSUNFR) THEN
  WRITE (KLUN) LBOUND (YD%RSUNFR)
  WRITE (KLUN) UBOUND (YD%RSUNFR)
  WRITE (KLUN) YD%RSUNFR
ENDIF
LRRH = ALLOCATED (YD%RRH)
WRITE (KLUN) LRRH
IF (LRRH) THEN
  WRITE (KLUN) LBOUND (YD%RRH)
  WRITE (KLUN) UBOUND (YD%RRH)
  WRITE (KLUN) YD%RRH
ENDIF
LRLWWEI = ALLOCATED (YD%RLWWEI)
WRITE (KLUN) LRLWWEI
IF (LRLWWEI) THEN
  WRITE (KLUN) LBOUND (YD%RLWWEI)
  WRITE (KLUN) UBOUND (YD%RLWWEI)
  WRITE (KLUN) YD%RLWWEI
ENDIF
END SUBROUTINE

SUBROUTINE LOAD_TAIOP (KLUN, YD)
USE PARKIND1, ONLY : JPRD

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TAIOP), INTENT (OUT), TARGET :: YD
INTEGER :: IL1(1), IU1(1), IL3(3), IU3(3)
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=JPRD), ALLOCATABLE :: ZTMP3 (:,:,:)
READ (KLUN) YD%NAEROMR
READ (KLUN) YD%NWAVSW
READ (KLUN) YD%NWAVLW
READ (KLUN) YD%NRELHU
READ (KLUN) LRSWAME
IF (LRSWAME) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSWAME (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RSWAME,1):UBOUND(YD%RSWAME,1), LBOUND(YD%RSWAME,2):UBOUND(YD%RSWAME,2), LBOUND(YD%RSWAME,3):UBOUND(YD%RSWAME,3)))
  READ (KLUN) ZTMP3
  YD%RSWAME = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRLWAME
IF (LRLWAME) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLWAME (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RLWAME,1):UBOUND(YD%RLWAME,1), LBOUND(YD%RLWAME,2):UBOUND(YD%RLWAME,2), LBOUND(YD%RLWAME,3):UBOUND(YD%RLWAME,3)))
  READ (KLUN) ZTMP3
  YD%RLWAME = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRSWAAS
IF (LRSWAAS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSWAAS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RSWAAS,1):UBOUND(YD%RSWAAS,1), LBOUND(YD%RSWAAS,2):UBOUND(YD%RSWAAS,2), LBOUND(YD%RSWAAS,3):UBOUND(YD%RSWAAS,3)))
  READ (KLUN) ZTMP3
  YD%RSWAAS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRLWAAS
IF (LRLWAAS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLWAAS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RLWAAS,1):UBOUND(YD%RLWAAS,1), LBOUND(YD%RLWAAS,2):UBOUND(YD%RLWAAS,2), LBOUND(YD%RLWAAS,3):UBOUND(YD%RLWAAS,3)))
  READ (KLUN) ZTMP3
  YD%RLWAAS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRSWASS
IF (LRSWASS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RSWASS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RSWASS,1):UBOUND(YD%RSWASS,1), LBOUND(YD%RSWASS,2):UBOUND(YD%RSWASS,2), LBOUND(YD%RSWASS,3):UBOUND(YD%RSWASS,3)))
  READ (KLUN) ZTMP3
  YD%RSWASS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRLWASS
IF (LRLWASS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (YD%RLWASS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(YD%RLWASS,1):UBOUND(YD%RLWASS,1), LBOUND(YD%RLWASS,2):UBOUND(YD%RLWASS,2), LBOUND(YD%RLWASS,3):UBOUND(YD%RLWASS,3)))
  READ (KLUN) ZTMP3
  YD%RLWASS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRSWWL
IF (LRSWWL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSWWL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RSWWL,1):UBOUND(YD%RSWWL,1)))
  READ (KLUN) ZTMP1
  YD%RSWWL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLWWL
IF (LRLWWL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLWWL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLWWL,1):UBOUND(YD%RLWWL,1)))
  READ (KLUN) ZTMP1
  YD%RLWWL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRSUNFR
IF (LRSUNFR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RSUNFR (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RSUNFR,1):UBOUND(YD%RSUNFR,1)))
  READ (KLUN) ZTMP1
  YD%RSUNFR = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRRH
IF (LRRH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RRH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RRH,1):UBOUND(YD%RRH,1)))
  READ (KLUN) ZTMP1
  YD%RRH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRLWWEI
IF (LRLWWEI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (YD%RLWWEI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(YD%RLWWEI,1):UBOUND(YD%RLWWEI,1)))
  READ (KLUN) ZTMP1
  YD%RLWWEI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
END SUBROUTINE


SUBROUTINE COPY_TAIOP (YD, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TAIOP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  GPU_CREATE(YD)
  GPU_UPDATE_DEVICE(YD)
ENDIF




LRSWAME = ALLOCATED (YD%RSWAME)
IF (LRSWAME) THEN
  GPU_CREATE(YD%RSWAME)
  GPU_UPDATE_DEVICE(YD%RSWAME)
  GPU_ATTACH(YD%RSWAME)
ENDIF

LRLWAME = ALLOCATED (YD%RLWAME)
IF (LRLWAME) THEN
  GPU_CREATE(YD%RLWAME)
  GPU_UPDATE_DEVICE(YD%RLWAME)
  GPU_ATTACH(YD%RLWAME)
ENDIF

LRSWAAS = ALLOCATED (YD%RSWAAS)
IF (LRSWAAS) THEN
  GPU_CREATE(YD%RSWAAS)
  GPU_UPDATE_DEVICE(YD%RSWAAS)
  GPU_ATTACH(YD%RSWAAS)
ENDIF

LRLWAAS = ALLOCATED (YD%RLWAAS)
IF (LRLWAAS) THEN
  GPU_CREATE(YD%RLWAAS)
  GPU_UPDATE_DEVICE(YD%RLWAAS)
  GPU_ATTACH(YD%RLWAAS)
ENDIF

LRSWASS = ALLOCATED (YD%RSWASS)
IF (LRSWASS) THEN
  GPU_CREATE(YD%RSWASS)
  GPU_UPDATE_DEVICE(YD%RSWASS)
  GPU_ATTACH(YD%RSWASS)
ENDIF

LRLWASS = ALLOCATED (YD%RLWASS)
IF (LRLWASS) THEN
  GPU_CREATE(YD%RLWASS)
  GPU_UPDATE_DEVICE(YD%RLWASS)
  GPU_ATTACH(YD%RLWASS)
ENDIF

LRSWWL = ALLOCATED (YD%RSWWL)
IF (LRSWWL) THEN
  GPU_CREATE(YD%RSWWL)
  GPU_UPDATE_DEVICE(YD%RSWWL)
  GPU_ATTACH(YD%RSWWL)
ENDIF

LRLWWL = ALLOCATED (YD%RLWWL)
IF (LRLWWL) THEN
  GPU_CREATE(YD%RLWWL)
  GPU_UPDATE_DEVICE(YD%RLWWL)
  GPU_ATTACH(YD%RLWWL)
ENDIF

LRSUNFR = ALLOCATED (YD%RSUNFR)
IF (LRSUNFR) THEN
  GPU_CREATE(YD%RSUNFR)
  GPU_UPDATE_DEVICE(YD%RSUNFR)
  GPU_ATTACH(YD%RSUNFR)
ENDIF

LRRH = ALLOCATED (YD%RRH)
IF (LRRH) THEN
  GPU_CREATE(YD%RRH)
  GPU_UPDATE_DEVICE(YD%RRH)
  GPU_ATTACH(YD%RRH)
ENDIF

LRLWWEI = ALLOCATED (YD%RLWWEI)
IF (LRLWWEI) THEN
  GPU_CREATE(YD%RLWWEI)
  GPU_UPDATE_DEVICE(YD%RLWWEI)
  GPU_ATTACH(YD%RLWWEI)
ENDIF

END SUBROUTINE

SUBROUTINE HOST_TAIOP (YD)

IMPLICIT NONE
TYPE (TAIOP), TARGET :: YD
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL















END SUBROUTINE

     

SUBROUTINE CRC64_TAIOP (YD, KLUN, CDPATH)
USE CRC64_INTRINSIC

IMPLICIT NONE
TYPE (TAIOP), TARGET :: YD
INTEGER, INTENT (IN) :: KLUN
CHARACTER(LEN=*), INTENT (IN) :: CDPATH
CHARACTER(LEN=128) :: CLIND
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL
WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NAEROMR), CDPATH//'%NAEROMR'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NWAVSW), CDPATH//'%NWAVSW'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NWAVLW), CDPATH//'%NWAVLW'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%NRELHU), CDPATH//'%NRELHU'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RSWAME), CDPATH//'%RSWAME'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLWAME), CDPATH//'%RLWAME'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RSWAAS), CDPATH//'%RSWAAS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLWAAS), CDPATH//'%RLWAAS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RSWASS), CDPATH//'%RSWASS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLWASS), CDPATH//'%RLWASS'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RSWWL), CDPATH//'%RSWWL'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLWWL), CDPATH//'%RLWWL'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RSUNFR), CDPATH//'%RSUNFR'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RRH), CDPATH//'%RRH'

WRITE (KLUN, '(Z16.16," ",A)') CRC64 (YD%RLWWEI), CDPATH//'%RLWWEI'

END SUBROUTINE

SUBROUTINE WIPE_TAIOP (YD, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TAIOP), INTENT (IN), TARGET :: YD
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL

LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF




LRSWAME = ALLOCATED (YD%RSWAME)
IF (LRSWAME) THEN
  GPU_DETACH(YD%RSWAME)
  GPU_DELETE(YD%RSWAME)
ENDIF

LRLWAME = ALLOCATED (YD%RLWAME)
IF (LRLWAME) THEN
  GPU_DETACH(YD%RLWAME)
  GPU_DELETE(YD%RLWAME)
ENDIF

LRSWAAS = ALLOCATED (YD%RSWAAS)
IF (LRSWAAS) THEN
  GPU_DETACH(YD%RSWAAS)
  GPU_DELETE(YD%RSWAAS)
ENDIF

LRLWAAS = ALLOCATED (YD%RLWAAS)
IF (LRLWAAS) THEN
  GPU_DETACH(YD%RLWAAS)
  GPU_DELETE(YD%RLWAAS)
ENDIF

LRSWASS = ALLOCATED (YD%RSWASS)
IF (LRSWASS) THEN
  GPU_DETACH(YD%RSWASS)
  GPU_DELETE(YD%RSWASS)
ENDIF

LRLWASS = ALLOCATED (YD%RLWASS)
IF (LRLWASS) THEN
  GPU_DETACH(YD%RLWASS)
  GPU_DELETE(YD%RLWASS)
ENDIF

LRSWWL = ALLOCATED (YD%RSWWL)
IF (LRSWWL) THEN
  GPU_DETACH(YD%RSWWL)
  GPU_DELETE(YD%RSWWL)
ENDIF

LRLWWL = ALLOCATED (YD%RLWWL)
IF (LRLWWL) THEN
  GPU_DETACH(YD%RLWWL)
  GPU_DELETE(YD%RLWWL)
ENDIF

LRSUNFR = ALLOCATED (YD%RSUNFR)
IF (LRSUNFR) THEN
  GPU_DETACH(YD%RSUNFR)
  GPU_DELETE(YD%RSUNFR)
ENDIF

LRRH = ALLOCATED (YD%RRH)
IF (LRRH) THEN
  GPU_DETACH(YD%RRH)
  GPU_DELETE(YD%RRH)
ENDIF

LRLWWEI = ALLOCATED (YD%RLWWEI)
IF (LRLWWEI) THEN
  GPU_DETACH(YD%RLWWEI)
  GPU_DELETE(YD%RLWWEI)
ENDIF

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  GPU_DELETE(YD)
ENDIF
END SUBROUTINE

INTEGER*8 FUNCTION SIZE_TAIOP (YD, CDPATH, LDPRINT) RESULT (KSIZE)

IMPLICIT NONE
TYPE (TAIOP),     INTENT (IN), TARGET :: YD
CHARACTER(LEN=*), INTENT (IN), OPTIONAL :: CDPATH
LOGICAL,          INTENT (IN), OPTIONAL :: LDPRINT
INTEGER*8 :: ISIZE, JSIZE
LOGICAL :: LLPRINT
CHARACTER(LEN=128) :: CLPATH
LOGICAL :: LRLWAAS, LRLWAME, LRLWASS, LRLWWEI, LRLWWL, LRRH, LRSUNFR, LRSWAAS, LRSWAME, LRSWASS
LOGICAL :: LRSWWL

LLPRINT = .FALSE.
IF (PRESENT (LDPRINT)) THEN
  LLPRINT = LDPRINT
ENDIF
CLPATH=''
IF (PRESENT (CDPATH)) THEN
  CLPATH = CDPATH
ENDIF
KSIZE = 0
ISIZE = KIND (YD%NAEROMR)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NAEROMR'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NWAVSW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NWAVSW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NWAVLW)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NWAVLW'
ENDIF
KSIZE = KSIZE + ISIZE
ISIZE = KIND (YD%NRELHU)
IF (LLPRINT) THEN
  WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
  WRITE (*, *) TRIM (CLPATH)//'%NRELHU'
ENDIF
KSIZE = KSIZE + ISIZE
LRSWAME = ALLOCATED (YD%RSWAME)
IF (LRSWAME) THEN
  ISIZE = KIND (YD%RSWAME) * SIZE (YD%RSWAME)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSWAME'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLWAME = ALLOCATED (YD%RLWAME)
IF (LRLWAME) THEN
  ISIZE = KIND (YD%RLWAME) * SIZE (YD%RLWAME)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLWAME'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSWAAS = ALLOCATED (YD%RSWAAS)
IF (LRSWAAS) THEN
  ISIZE = KIND (YD%RSWAAS) * SIZE (YD%RSWAAS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSWAAS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLWAAS = ALLOCATED (YD%RLWAAS)
IF (LRLWAAS) THEN
  ISIZE = KIND (YD%RLWAAS) * SIZE (YD%RLWAAS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLWAAS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSWASS = ALLOCATED (YD%RSWASS)
IF (LRSWASS) THEN
  ISIZE = KIND (YD%RSWASS) * SIZE (YD%RSWASS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSWASS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLWASS = ALLOCATED (YD%RLWASS)
IF (LRLWASS) THEN
  ISIZE = KIND (YD%RLWASS) * SIZE (YD%RLWASS)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLWASS'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSWWL = ALLOCATED (YD%RSWWL)
IF (LRSWWL) THEN
  ISIZE = KIND (YD%RSWWL) * SIZE (YD%RSWWL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSWWL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLWWL = ALLOCATED (YD%RLWWL)
IF (LRLWWL) THEN
  ISIZE = KIND (YD%RLWWL) * SIZE (YD%RLWWL)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLWWL'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRSUNFR = ALLOCATED (YD%RSUNFR)
IF (LRSUNFR) THEN
  ISIZE = KIND (YD%RSUNFR) * SIZE (YD%RSUNFR)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RSUNFR'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRRH = ALLOCATED (YD%RRH)
IF (LRRH) THEN
  ISIZE = KIND (YD%RRH) * SIZE (YD%RRH)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RRH'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
LRLWWEI = ALLOCATED (YD%RLWWEI)
IF (LRLWWEI) THEN
  ISIZE = KIND (YD%RLWWEI) * SIZE (YD%RLWWEI)
  IF (LLPRINT) THEN
    WRITE (*, '(I10," ")', ADVANCE='NO') ISIZE
    WRITE (*, *) TRIM (CLPATH)//'%RLWWEI'
  ENDIF
  KSIZE = KSIZE + ISIZE
ENDIF
END FUNCTION

END MODULE
